export const languages = [
  { label: "Bash", value: "bash" },
  { label: "C", value: "c" },
  { label: "C++", value: "cpp" },
  { label: "C#", value: "csharp" },
  { label: "CSS", value: "css" },
  { label: "diff", value: "diff" },
  { label: "Go", value: "go" },
  { label: "GraphQL", value: "graphql" },
  { label: "ini", value: "ini" },
  { label: "Java", value: "java" },
  { label: "Javascript", value: "javascript" },
  { label: "JSON", value: "json" },
  { label: "Kotlin", value: "kotlin" },
  { label: "less", value: "less" },
  { label: "Lua", value: "lua" },
  { label: "Makefile", value: "makefile" },
  { label: "Markdown", value: "markdown" },
  { label: "Objective-c", value: "objectivec" },
  { label: "Perl", value: "perl" },
  { label: "PHP Template", value: "php-template" },
  { label: "PHP", value: "php" },
  { label: "Plain Text", value: "plaintext" },
  { label: "Python REPL", value: "python-repl" },
  { label: "Python", value: "python" },
  { label: "R", value: "r" },
  { label: "Ruby", value: "ruby" },
  { label: "Rust", value: "rust" },
  { label: "SCSS", value: "scss" },
  { label: "Shell", value: "shell" },
  { label: "SQL", value: "sql" },
  { label: "Swift", value: "swift" },
  { label: "Typescript", value: "typescript" },
  { label: "VB.Net", value: "vbnet" },
  { label: "WASM", value: "wasm" },
  { label: "XML", value: "xml" },
  { label: "YAML", value: "yaml" },
];
